# Generated by Django 5.2.7 on 2025-10-21 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_membertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'hoo'), (2, 'admin'), (3, 'subadmin')], max_length=25),
        ),
    ]
