# Generated by Django 5.2.7 on 2025-10-23 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'hoo'), (2, 'sys_admin'), (3, 'sub_admin')], max_length=25),
        ),
    ]
