# Generated by Django 5.2.7 on 2025-10-23 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'hoo'), (2, 'sysadmin'), (3, 'subadmin')], max_length=25),
        ),
    ]
