# Generated by Django 5.2.7 on 2025-10-23 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_registration_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RifdAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('invalid', 'Invalid')], default='valid', max_length=10)),
                ('in_use', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
