# Generated by Django 5.2.7 on 2025-10-23 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_barangay_municipality_province_delete_registration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('l_name', models.CharField(max_length=100)),
                ('f_name', models.CharField(max_length=100)),
                ('m_name', models.CharField(blank=True, max_length=100, null=True)),
                ('name_extension', models.CharField(blank=True, max_length=10, null=True)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=255)),
                ('mobile_no', models.CharField(max_length=20)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('barangay_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.barangay')),
                ('municipality_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.municipality')),
                ('province_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.province')),
            ],
        ),
    ]
