# Generated by Django 5.2.7 on 2025-10-23 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_registration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barangay',
            old_name='municipality_id',
            new_name='municipality',
        ),
        migrations.RenameField(
            model_name='municipality',
            old_name='province_id',
            new_name='province',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='barangay_id',
            new_name='barangay',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='municipality_id',
            new_name='municipality',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='province_id',
            new_name='province',
        ),
    ]
