# Generated by Django 5.2.7 on 2025-10-25 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_municipality_id_barangay_municipality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
