# Generated by Django 5.2.7 on 2025-10-25 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_registration_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='f_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='l_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='m_name',
            new_name='middle_name',
        ),
    ]
