# Generated by Django 5.2.7 on 2025-10-25 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_f_name_registration_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='profile',
            new_name='profile_pic',
        ),
    ]
