# Generated by Django 5.2.7 on 2025-10-25 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_profile_registration_profile_pic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RifdAuth',
            new_name='RfidAuth',
        ),
    ]
