# Generated by Django 5.2.7 on 2025-10-29 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_rifdauth_rfidauth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('date_expiry', models.DateField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='registration',
            name='civil_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('1', 'hoo'), ('2', 'sysadmin'), ('3', 'subadmin')], max_length=25),
        ),
        migrations.CreateModel(
            name='bsrcenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_claimed', models.DateField(auto_now_add=True)),
                ('date_claim_expiry', models.DateField()),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.registration')),
                ('medicines', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.medicines')),
            ],
        ),
    ]
