# Generated by Django 5.2.7 on 2025-10-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_medicines_registration_civil_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
