# Generated by Django 5.2.7 on 2025-10-29 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_registration_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='rfid',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
