# Generated by Django 5.2.7 on 2025-10-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_registration_email_alter_registration_rfid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('1', 'hoo'), ('2', 'sysadmin'), ('3', 'municipaladmin'), ('4', 'subadmin')], max_length=25),
        ),
    ]
