# Generated by Django 5.2.7 on 2025-10-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('1', 'hoo'), ('2', 'sysadmin'), ('3', 'municipaladmin'), ('4', 'admincenter'), ('5', 'centerstaff')], max_length=25),
        ),
    ]
