# Generated by Django 5.2.7 on 2025-10-29 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_customuser_user_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bsrcenter',
        ),
    ]
