# Generated by Django 5.2.7 on 2025-10-29 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_delete_bsrcenter'),
    ]

    operations = [
        migrations.CreateModel(
            name='bsrcenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_claimed', models.DateField(auto_now_add=True)),
                ('date_claim_expiry', models.DateField()),
                ('medicines', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.medicines')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.registration')),
            ],
        ),
    ]
