# Generated by Django 5.2.7 on 2025-10-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_bsrcenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='bsrcenter',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
