# Generated by Django 5.2.7 on 2025-11-04 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_bsrcenter_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bsrcenter',
            name='medicines',
        ),
        migrations.AddField(
            model_name='bsrcenter',
            name='barangay_indigency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bsrcenter',
            name='barangay_recidency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bsrcenter',
            name='tracking_number',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Bsrcenter_meds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bsrcenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bsrcenter')),
                ('medicines', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.medicines')),
            ],
        ),
    ]
