# Generated by Django 5.2.7 on 2025-11-04 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_remove_bsrcenter_medicines_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bsrcenter',
            name='diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bsrcenter',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
