# Generated by Django 5.2.8 on 2025-11-08 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_bsrcenter_diagnosis_alter_bsrcenter_tracking_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bsrcenter_Burial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('deceased_name', models.CharField(max_length=255)),
                ('relationship', models.CharField(max_length=100)),
                ('date_claimed', models.DateField(auto_now_add=True)),
                ('date_claim_expiry', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('death_certificate', models.BooleanField(default=False)),
                ('cause_of_death', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.registration')),
            ],
        ),
    ]
