# Generated by Django 5.2.8 on 2025-11-08 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
    ]
