# Generated by Django 5.2.8 on 2025-11-08 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bsrcenter',
            name='status',
        ),
    ]
