# Generated by Django 5.2.8 on 2025-11-08 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_remove_bsrcenter_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bsrcenter',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.status'),
        ),
    ]
