# Generated by Django 5.2.8 on 2025-11-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_bsrcenter_burial_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('1', 'hoo'), ('2', 'sysadmin'), ('3', 'municipaladmin'), ('4', 'admincenter'), ('5', 'centerstaff'), ('6', 'adminpeso'), ('7', 'pesostaff')], max_length=25),
        ),
    ]
