# Generated by Django 5.2.8 on 2025-11-08 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_bsrcenter_released_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='bsrcenter_burial',
            name='released_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
