# Generated by Django 5.2.8 on 2025-11-08 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_bsrcenter_burial_released_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peso_reap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biodata', models.BooleanField(default=False)),
                ('certificate_of_reg', models.BooleanField(default=False)),
                ('certificate_of_grades', models.BooleanField(default=False)),
                ('barangay_indigency', models.BooleanField(default=False)),
                ('barangay_recidency', models.BooleanField(default=False)),
                ('offical_receipt', models.BooleanField(default=False)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.registration')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
