# Generated by Django 5.2.8 on 2025-11-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_peso_reap'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peso_reap',
            old_name='offical_receipt',
            new_name='official_receipt',
        ),
        migrations.AddField(
            model_name='peso_reap',
            name='date_added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
