# Generated by Django 5.2.8 on 2025-11-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_rename_offical_receipt_peso_reap_official_receipt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bsrcenter',
            old_name='released_by',
            new_name='processed_by',
        ),
        migrations.RenameField(
            model_name='bsrcenter_burial',
            old_name='released_by',
            new_name='processed_by',
        ),
        migrations.RenameField(
            model_name='peso_reap',
            old_name='released_by',
            new_name='processed_by',
        ),
        migrations.AddField(
            model_name='peso_reap',
            name='is_released',
            field=models.BooleanField(default=False),
        ),
    ]
