# Generated by Django 5.2.8 on 2025-11-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_rename_released_by_bsrcenter_processed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peso_reap',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
