# Generated by Django 5.2.8 on 2025-11-08 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_peso_reap_tracking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='peso_reap',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.status'),
        ),
    ]
