# Generated by Django 5.2.8 on 2025-11-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_peso_reap_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
