# Generated by Django 5.2.8 on 2025-11-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_registration_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='zone_street',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
