# Generated by Django 5.2.8 on 2025-11-10 01:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_registration_zone_street'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills_training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Skills_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='peso_reap',
            name='date_claim_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='peso_reap',
            name='date_claimed',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='Peso_tupad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('date_claimed', models.DateField(auto_now_add=True)),
                ('date_claim_expiry', models.DateField()),
                ('name_of_beneficiary', models.CharField(max_length=255)),
                ('is_released', models.BooleanField(default=False)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.registration')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.status')),
                ('skills_training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.skills_training')),
            ],
        ),
    ]
