# Generated by Django 5.2.8 on 2025-11-10 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_skills_training_peso_reap_date_claim_expiry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills_training',
            name='description',
        ),
    ]
