# Generated by Django 5.2.8 on 2025-11-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_remove_skills_training_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='year_cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sy_start', models.DateField()),
                ('sy_end', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('1', 'hoo'), ('2', 'sysadmin'), ('3', 'municipaladmin'), ('4', 'admincenter'), ('5', 'centerstaff'), ('6', 'adminpeso'), ('7', 'pesostaff'), ('8', 'module1')], max_length=25),
        ),
    ]
