# Generated by Django 5.2.8 on 2025-11-14 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_year_cycle_alter_customuser_user_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='year_cycle',
            new_name='Academic_year',
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem_name', models.CharField(max_length=100)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.academic_year')),
            ],
        ),
    ]
