# Generated by Django 5.2.8 on 2025-11-14 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_rename_year_cycle_academic_year_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='peso_reap',
            name='Academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.academic_year'),
        ),
        migrations.AddField(
            model_name='peso_reap',
            name='Semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.semester'),
        ),
    ]
