# Generated by Django 5.2.8 on 2025-11-14 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_peso_reap_academic_year_peso_reap_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='peso_reap',
            name='next',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='user_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.user_type'),
        ),
    ]
