# Generated by Django 5.2.8 on 2025-11-14 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_user_type_peso_reap_next_registration_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='End_user_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_user_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='registration',
            name='user_type',
        ),
        migrations.AddField(
            model_name='registration',
            name='end_user_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.end_user_type'),
        ),
        migrations.DeleteModel(
            name='user_type',
        ),
    ]
