# Generated by Django 5.2.8 on 2025-11-15 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_end_user_type_remove_registration_user_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academic_year',
            old_name='sy_end',
            new_name='ay_end',
        ),
        migrations.RenameField(
            model_name='academic_year',
            old_name='sy_start',
            new_name='ay_start',
        ),
    ]
