# Generated by Django 5.2.8 on 2025-11-15 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_rename_sy_end_academic_year_ay_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='academic_year',
        ),
        migrations.AddField(
            model_name='academic_year',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.semester'),
        ),
    ]
