# Generated by Django 5.2.8 on 2025-11-15 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_remove_semester_academic_year_academic_year_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic_year',
            name='ay_start',
            field=models.DateField(unique=True),
        ),
    ]
