# Generated by Django 5.2.8 on 2025-11-15 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_alter_academic_year_ay_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peso_reap',
            name='Semester',
        ),
    ]
