# Generated by Django 5.2.8 on 2025-11-15 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_remove_peso_reap_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peso_reap',
            name='date_claim_expiry',
        ),
        migrations.RemoveField(
            model_name='peso_reap',
            name='date_claimed',
        ),
    ]
