# Generated by Django 5.2.8 on 2025-11-15 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_remove_peso_reap_date_claim_expiry_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academic_year',
            old_name='ay_start',
            new_name='year',
        ),
        migrations.RemoveField(
            model_name='academic_year',
            name='ay_end',
        ),
    ]
