# Generated by Django 5.2.8 on 2025-11-15 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_rename_ay_start_academic_year_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reap_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='peso_reap',
            name='reap_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.reap_type'),
        ),
    ]
