# Generated by Django 5.2.8 on 2025-11-20 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_reap_type_peso_reap_reap_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='rfidauth',
            name='registration',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.registration'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='occupation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.occupation'),
        ),
    ]
