# Generated by Django 5.2.8 on 2025-11-20 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_occupation_rfidauth_registration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfidauth',
            name='registration',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.registration'),
        ),
    ]
