# Generated by Django 5.2.8 on 2025-11-20 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_alter_rfidauth_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfidauth',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.registration'),
        ),
    ]
