# Generated by Django 5.2.8 on 2025-11-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_alter_rfidauth_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Civil_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civil_status_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='registration',
            name='civil_status',
        ),
    ]
