# Generated by Django 5.2.8 on 2025-11-20 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_civil_status_remove_registration_civil_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='civil_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.civil_status'),
        ),
    ]
