# Generated by Django 5.2.8 on 2025-11-21 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_registration_civil_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peso_tupad',
            old_name='date_claimed',
            new_name='date_issued',
        ),
        migrations.RenameField(
            model_name='peso_tupad',
            old_name='date_claim_expiry',
            new_name='date_issued_expiry',
        ),
    ]
