# Generated by Django 5.2.8 on 2025-11-21 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_rename_date_claimed_peso_tupad_date_issued_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bsrcenter',
            name='actioned_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='bsrcenter',
            name='actioned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actioned_bsrcenters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bsrcenter_burial',
            name='actioned_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='bsrcenter_burial',
            name='actioned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actioned_bsrcenter_burials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='peso_reap',
            name='actioned_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='peso_reap',
            name='actioned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actioned_peso_reaps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='peso_tupad',
            name='actioned_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='peso_tupad',
            name='actioned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actioned_peso_tupads', to=settings.AUTH_USER_MODEL),
        ),
    ]
