# Generated by Django 5.2.8 on 2025-11-27 02:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_bsrcenter_actioned_at_bsrcenter_actioned_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peso_reap',
            name='released_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='peso_reap',
            name='released_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='released_peso_reaps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='peso_tupad',
            name='released_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='peso_tupad',
            name='released_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='released_peso_tupads', to=settings.AUTH_USER_MODEL),
        ),
    ]
