# Generated by Django 5.2.8 on 2025-12-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_peso_reap_released_at_peso_reap_released_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bsrcenter',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bsrcenter_burial',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='peso_reap',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='peso_tupad',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
