# Generated by Django 5.2.8 on 2025-12-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0068_bsrcenter_is_completed_bsrcenter_burial_is_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_release',
            field=models.BooleanField(default=False),
        ),
    ]
