# Generated by Django 5.2.8 on 2025-12-04 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0069_customuser_can_release'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('1', 'hoo'), ('2', 'sysadmin'), ('3', 'municipaladmin'), ('4', 'admincenter'), ('5', 'centerstaff'), ('6', 'adminpeso'), ('7', 'pesostaff'), ('8', 'admindswd'), ('9', 'dswdstaff')], max_length=25),
        ),
    ]
