# Generated by Django 5.2.8 on 2025-12-04 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0070_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='ncsc_rrn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='osca_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
