# Generated by Django 5.2.8 on 2025-12-04 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0071_registration_ncsc_rrn_registration_osca_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dswd_senior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barangay_indigency', models.BooleanField(default=False)),
                ('date_issued', models.DateField(auto_now_add=True)),
                ('date_issued_expiry', models.DateField()),
                ('date_registered', models.DateField(auto_now_add=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.registration')),
            ],
        ),
    ]
