# Generated by Django 5.2.8 on 2025-12-04 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0072_dswd_senior'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dswd_senior',
            name='date_registered',
        ),
        migrations.AddField(
            model_name='dswd_senior',
            name='actioned_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='dswd_senior',
            name='actioned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actioned_dswd_seniors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dswd_senior',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dswd_senior',
            name='is_released',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dswd_senior',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dswd_senior',
            name='released_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='dswd_senior',
            name='released_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='released_dswd_seniors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dswd_senior',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.status'),
        ),
    ]
