# Generated by Django 5.2.8 on 2025-12-04 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0073_remove_dswd_senior_date_registered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dswd_senior',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
